### ISSUE TITLE
Browsing to account results in "File not found" error page

### ISSUE THREAD

**Issue by mrstegeman** [nextcloud/social#229] opened 2018-12-14 18:12 UTC
**Describe the bug**

After creating the post, I click on the link above it in the timeline and end up with a "File not found" error, instead of the account page.

**To Reproduce**

1. Go to Social app
2. Create a public post
3. Go to any of the timeline pages, i.e. Profile, Local timeline, or Global timeline
4. Click on link above post, i.e. https://myhost.com/index.php/apps/social/@myuser

**Expected behavior**

Account/profile page should be displayed

**Screenshots**

![screenshot_2018-12-14 nextcloud](https://user-images.githubusercontent.com/457381/50019478-ba5e0280-ffca-11e8-91e4-ad353f707c20.png)

**Client details:**

 - OS: macOS
 - Browser: Firefox
 - Version: 64
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version:** 0.1.0

**Operating system:** Official Docker image

**Web server:** Apache

**Database:** mariadb 10.3.11

**PHP version:** 7.2

**Nextcloud version:** 15.0.0

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"zN5FZ7w1xqxfw63gxhIY","level":0,"time":"2018-12-14T18:06:41+00:00","remoteAddr":"172.20.0.2","user":"michael","app":"no app in context","method":"GET","url":"\/index.php\/apps\/social\/@michael","message":"No cache entry found for \/appdata_ocvfkofw8r5z\/theming\/images\/background (storage: local::\/var\/www\/html\/data\/, internalPath: appdata_ocvfkofw8r5z\/theming\/images\/background)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.0.10"}
{"reqId":"3pKrOWrSegabdfv5gi9F","level":0,"time":"2018-12-14T18:06:45+00:00","remoteAddr":"172.20.0.2","user":"michael","app":"no app in context","method":"GET","url":"\/index.php\/css\/icons\/icons-vars.css?v=1544791945","message":"No cache entry found for \/appdata_ocvfkofw8r5z\/css\/icons\/icons-vars.css.gzip (storage: local::\/var\/www\/html\/data\/, internalPath: appdata_ocvfkofw8r5z\/css\/icons\/icons-vars.css.gzip)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.0.10"}
```

#### Browser log
```
18:05:42.434 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
18:05:44.096 JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
```

</details>

**Comment by jancborchardt** [comment] 2018-12-14 23:45
@mrstegeman thanks for the report, this issue has already been opened at https://github.com/nextcloud/social/issues/173 :)

**Comment by mrstegeman** [comment] 2018-12-14 23:56
@jancborchardt It’s close, but for me, it doesn’t even work with just the `@user` case.

**Comment by jancborchardt** [comment] 2018-12-15 10:58
@mrstegeman right, might be different. Do you have more info like server logs?

cc @daita

**Comment by juliushaertl** [comment] 2018-12-19 09:10
Fix is included in #244

**Closed** 2018-12-20 14:18 UTC
Labels: 4. to release, bug

**Comment by mrstegeman** [comment] 2018-12-22 15:16
@jancborchardt After updating to the new 0.1.1 release, I tried again. Unfortunately, I still have issues. Now, I get a "User not found" error page, both when logged in and logged out.

![screenshot_2018-12-22 social - nextcloud](https://user-images.githubusercontent.com/457381/50375873-99199980-05fc-11e9-9885-f3d8bf52aafb.png)

**Comment by juliushaertl** [comment] 2018-12-22 20:34
@mrstegeman I cannot reproduce this here, any errors in the logs? Can you try a hard refresh, maybe it is a javascript caching issue?

**Comment by mrstegeman** [comment] 2018-12-22 20:59
Hard refresh didn’t help, but I do have the following in the log:

```
Warning: 500 - {"status":-1,"exception":"OCA\\Social\\Exceptions\\CacheActorDoesNotExistException","message":""}
```

**Comment by mrstegeman** [comment] 2018-12-22 21:00
Just FYI: I’m using the official Docker image, sitting behind Traefik. Do I maybe have something misconfigured?

**Comment by juliushaertl** [comment] 2018-12-22 21:17
Is it your own account you are trying to browse there? Can you try running: `php occ social:cache:refresh` ?

**Comment by mrstegeman** [comment] 2018-12-23 02:20
@juliushaertl Yes, it's my own local account that I'm logged into.

```bash
$ php occ social:cache:refresh
An unhandled exception has been thrown:
TypeError: Argument 3 passed to OC\Accounts\Account::setProperty() must be of the type string, null given, called in /var/www/html/lib/private/Accounts/AccountManager.php on line 333 and defined in /var/www/html/lib/private/Accounts/Account.php:46
Stack trace:
#0 /var/www/html/lib/private/Accounts/AccountManager.php(333): OC\Accounts\Account->setProperty('displayname', 'Michael Stegema...', NULL, '0')
#1 /var/www/html/lib/private/Accounts/AccountManager.php(339): OC\Accounts\AccountManager->parseAccountData(Object(OC\User\User), Array)
#2 /var/www/html/custom_apps/social/lib/Service/AccountService.php(273): OC\Accounts\AccountManager->getAccount(Object(OC\User\User))
#3 /var/www/html/custom_apps/social/lib/Service/AccountService.php(240): OCA\Social\Service\AccountService->updateCacheLocalActorName(Object(OCA\Social\Model\ActivityPub\Actor\Person))
#4 /var/www/html/custom_apps/social/lib/Service/AccountService.php(304): OCA\Social\Service\AccountService->cacheLocalActorByUsername('michael', true)
#5 /var/www/html/custom_apps/social/lib/Command/CacheRefresh.php(105): OCA\Social\Service\AccountService->manageCacheLocalActors()
#6 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Social\Command\CacheRefresh->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Social\Command\CacheRefresh), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/console.php(96): OC\Console\Application->run()
#13 /var/www/html/occ(11): require_once('/var/www/html/c...')
#14 {main}
```

I also ran the new `occ social:reset` command, but ended up with the same "User not found" error page.

**Comment by juliushaertl** [comment] 2018-12-23 15:36
It is actually a server bug, if there is no visibility or scope set for the display name. See https://github.com/nextcloud/server/pull/13240 for a fix

**Comment by mrstegeman** [comment] 2018-12-23 19:38
Thanks! I’ll give it a shot again when there is a new server release.

**Comment by abmurksi** [comment] 2019-02-06 17:38
It has been fixed and backported to NC15: https://github.com/nextcloud/server/pull/13252
