### ISSUE TITLE
Following from mastodon is not possible

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/social#268] opened 2018-12-23 08:17 UTC
**Describe the bug**
When trying to follow https://mastodon.xyz/@nextcloud via the "Follow" button, i get an error which says
"Could not find the required redirect URL for your account", after I enter my cloud ID ("dartcafe@nc15.yagst.de").

Calling https://nc15.yagst.de/.well-known/webfinger?resource=acct:dartcafe@nc15.yagst.de gives a JSON:

`{"subject":"acct:dartcafe@nc15.yagst.de","links":[{"rel":"self","type":"application\/activity+json","href":"https:\/\/nc15.yagst.de\/index.php\/apps\/social\/@dartcafe\/"}]}`

Any idea, what I can do? There is no log entry, debug level.

**To Reproduce**
1. fresh install of social 0.1.1
2. Click on 'Follow Nextcloud on mastodon.xyz' --> Error
![grafik](https://user-images.githubusercontent.com/26707476/50381900-cadd3f80-0692-11e9-98ab-24e4f8fc0a44.png)
3. Switch to profile
But it seems, that I follow nextcloud. There are no posts visible (not sure, if there should be some on my startpage).
![grafik](https://user-images.githubusercontent.com/26707476/50381905-e5afb400-0692-11e9-9d60-f6c50b24698f.png)
4. Trying to follow from mastodon
![grafik](https://user-images.githubusercontent.com/26707476/50381916-0c6dea80-0693-11e9-965d-cfc25e41f842.png)

**Social app version:**
0.1.1
**Operating system**:
Linus
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**Comment by MagicFab** [comment] 2018-12-24 15:03
Same here, I was able to reproduce this problem.
However, if someone follows me from Mastodon, I can follow them back when they show up at
https://mynextcloud/index.php/apps/social/@myuser/followers

**Comment by LeoSum8** [comment] 2018-12-27 11:59
I see a similar behavior for my nextcloud instance.

Also when I use the mastodon search function on https://mastodon.cloud, I can see the following entries in my access-log:
```
195.201.111.25 - - [27/Dec/2018:12:19:11 +0100] "GET /.well-known/webfinger?resource=acct:leonhard@coleburn.servebeer.com HTTP/1.1" 302 303
195.201.111.25 - - [27/Dec/2018:12:19:11 +0100] "GET /nextcloud/public.php?service=webfinger&resource=acct:leonhard@coleburn.servebeer.com HTTP/1.1" 200 202
195.201.111.25 - - [27/Dec/2018:12:19:11 +0100] "GET /nextcloud/index.php/apps/social/@leonhard/ HTTP/1.1" 200 1641
195.201.111.25 - - [27/Dec/2018:12:19:11 +0100] "GET /apps/social/@leonhard HTTP/1.1" 404 219
195.201.111.25 - - [27/Dec/2018:12:19:11 +0100] "GET /apps/social/@leonhard HTTP/1.1" 404 219
```

Is it possible that somehow the `/nextcloud/` subfolder is lost on the way?

Like @dartcafe mentioned, manually calling the webfinger (in my case https://coleburn.servebeer.com/nextcloud/public.php?service=webfinger&resource=acct:leonhard@coleburn.servebeer.com) delivers the correct response (https://coleburn.servebeer.com/nextcloud/index.php/apps/social/@leonhard/)

However I CAN follow users from other mastodon instances by using the nextcloud search function and then clicking FOLLOW. But I don't seem to appear in their follower list.

Also, I cannot send direct messages back and forth.

My global timeline is also completely empty, I would expect to see messages from the followed accounts from time to time.

**Comment by vasyugan** [comment] 2019-01-01 14:35
I see the same issue with a nextcloud instance running on nginx, obviously, there is no .htaccess here. As per [the nginx config instructions](https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html), I have uncommented 
```
    rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
    last;
 
```
As webfinger seems to be what is important her, I have also sinderte the line

`    rewrite ^/.well-known/webfinger /public.php?service=webfinger&$1 last;
`

**Comment by Scumpeter** [comment] 2019-01-04 22:49
When you compare the json output of the social app to the output of other mastodon instances [1], you'll notice that they give a lot more information. I think the part that looks the most like a subscription link is:
`
5 |  
-- | --
rel | "http://ostatus.org/schema/1.0/subscribe"
template | "https://mastodon.xyz/authorize_interaction?uri={uri}"
`

[1] https://mastodon.xyz/.well-known/webfinger?resource=acct:nextcloud@mastodon.xyz

**Comment by vasyugan** [comment] 2019-01-05 12:32
> When you compare the json output of the social app to the output of other mastodon instances [1], you'll notice that they give a lot more information. 

Indeed, you're right. But it seems for some, Nextcloud social is working, isn't it? I can't imagine they released something that is just not functional yet.

**Comment by sirl1on** [comment] 2019-01-05 15:49
Can also reproduce this.

Running nextcloud social on nextcloud.spinweb.de without subfolder.

Having the following in my nginx config:

`rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

    location = /.well-known/carddav {
      return 301 $scheme://$host/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host/remote.php/dav;
    }
    location = /.well-known/webfinger {
      return 301 $scheme://$host/public.php?service=webfinger;
    }
`
Anything I could do to help track this bug down?

**Comment by daita** [comment] 2019-01-06 12:03
@sirl1on I think there is some documentation [somewhere](https://github.com/nextcloud/documentation/pull/1024/files) on how to enable the webfinger on nginx

**Comment by vasyugan** [comment] 2019-01-06 12:19
Am 06.01.19 um 13:03 schrieb Maxence Lange:
>
> @sirl1on <https://github.com/sirl1on> I think there is some
> documentation somewhere
> <https://github.com/nextcloud/documentation/pull/1024/files> on how to
> enable the webfinger on nginx
>

Yes, and it is enabled. See my comment above. Webfinger works. But what
the Nextcloud social app returns seems to be incomplete

**Comment by daita** [comment] 2019-01-07 08:11
Can you describe me your process of following someone ? I am not able to reproduce the bug on my side.

**Comment by vasyugan** [comment] 2019-01-07 08:19
Am 07.01.19 um 09:11 schrieb Maxence Lange:
>
> Can you describe me your process of following someone ? I am not able
> to reproduce the bug on my side.
>

Go to e.g. https://mastodon.xyz/@nextcloud

Click the "follow" button

Enter [username]@[nextcloud domain]

Btw, my nextcloud is /not/ in a subdir

**Comment by daita** [comment] 2019-01-07 08:34
Thanks !

Can confirm that this way of following someone is not implemented (yet) into Nextcloud Social.
Please search for the remote account in your Nextcloud Social, and click on Follow.

**Comment by vasyugan** [comment] 2019-01-07 08:41
I don't see a follow button there. Am I overlooking something?

**Comment by vasyugan** [comment] 2019-01-07 09:09
I see now what you mean, but first I have to bring up the user profile, and since I don't see a search function, the workaround is to manually enter the URL https://cloud.XXX/apps/social/@REMOTEUSER@REMOTEHOST/
(works for some profiles, but not for others. E.g failed to follow fsf@status.fsf.org

**Comment by daita** [comment] 2019-01-07 09:14
there is a searchbar at the top of the screen !

**Comment by vasyugan** [comment] 2019-01-07 09:19
> there is a searchbar at the top of the screen !

Thanks. Seems to work only for mastodon instances. e.g searching for fsf@status.fsf.org (which is on GNU social or status.net or something) returns no results. But that's probably a different bug already.

**Comment by daita** [comment] 2019-01-07 09:19
also: https://status.fsf.org/.well-known/webfinger?resource=acct:fsf@status.fsf.org

I cannot see any support for ActivityPub

**Comment by emersonkfuri** [comment] 2019-01-07 18:43
@daita ... Modifying webfinger.php to add rel => "http://ostatus.org/schema/1.0/subscribe", I was able to follow nextcloud@mastodon.xyz using step 4.

My mod:

```
diff -ru a/lib/webfinger.php b/lib/webfinger.php
--- a/lib/webfinger.php	2019-01-07 16:41:42.815526249 -0200
+++ b/lib/webfinger.php	2019-01-07 16:41:41.296517992 -0200
@@ -75,6 +75,10 @@
 			'rel'  => 'self',
 			'type' => 'application/activity+json',
 			'href' => $href
+		],
+		[
+			'rel' => 'http://ostatus.org/schema/1.0/subscribe',
+			'template' => $urlGenerator->getBaseURL() . '/apps/social/@{uri}'
 		]
 	]
 ];

```

**Comment by daita** [comment] 2019-01-07 19:23
Sorry, was working on this this morning, haven't pushed.

**Comment by daita** [comment] 2019-01-07 19:53
@vasyugan Please have a look to this: https://github.com/w3c/activitypub/issues/228. There is no issue implementing some feature from OStatus, but we will focus on ActivityPub

**Comment by aliceinwire** [comment] 2019-02-20 19:11
I get this issue

```
Error | Only variables should be passed by reference at /var/www/html/custom_apps/social/lib/Command/QueueProcess.php#97 |  
-- | -- | --

Warning | 500  -  {"status":-1,"exception":"OCA\\Social\\Exceptions\\RequestServerException","message":"500  -  {\"host\":\"status.fsf.org\",\"url\":\"\/.well-known\/webfinger\",\"timeout\":10,\"type\":0,\"data\":{\"resource\":\"acct:fsf@status.fsf.org\"}}"} |  
-- | -- | --

```

**Comment by daita** [comment] 2019-07-04 13:18
still having issue with 0.2.6 ?

**Comment by aliceinwire** [comment] 2019-07-04 17:47
let me check

**Comment by aliceinwire** [comment] 2019-07-04 17:54
dosen't change for me

**Comment by aliceinwire** [comment] 2019-07-04 17:58
works for me.
I can follow most of my mastodon contacts now.

**Comment by aliceinwire** [comment] 2019-07-04 18:08
but pleroma and status.fsf.org dosen't work

**Comment by daita** [comment] 2019-07-04 18:41
any account I can try ?

**Comment by aliceinwire** [comment] 2019-07-04 18:45
https://status.fsf.org/fsf
https://pleroma.soykaf.com/main/ostatus

**Comment by daita** [comment] 2019-07-04 19:02
thanks for those links. I will fix the issue with pleroma, however `GNU social`, used on status.fsf.org, appears to not being compatible with ActivityPub

**Comment by vasyugan** [comment] 2019-07-04 21:47
Some Mastodon instances seem to work now, some GNUsocial instances still
don't, for instance I tried to subscribe to @rms@gnusocial.no, which works
from a real Mastodon account but fails from Nextcloud social

Alice Ferrazzi <notifications@github.com> schrieb am Do., 4. Juli 2019,
20:45:

**Comment by shtrom** [comment] 2019-07-05 02:15
Following Mastodon instances seems to work, but I have the same issue as reported above with status.fsf.org, as well as a Twitter mirror I cannot recall the URL of (I'll try to find it).

I also don't seem to be able to reply to message from their Mastodon host:
* https://mastodon.host/interact/101838609146605306?type=reply
* leads me to a 404: `The requested URL /apps/social/ostatus/follow/https://mamot.fr/users/isa_attard/statuses/101838609151484448 was not found on this server.`

**Comment by daita** [comment] 2019-08-22 15:30
Unfortunately, gnusocial is not using ActivityPub (yet ?)

I will close this issue for now if the only problem is to interact with instance of gnusocial (like status.fsf.org)

**Closed by daita** 2019-08-22 15:30 UTC
Labels: bug, fixed ?
