### ISSUE TITLE
Import/export account

### ISSUE THREAD

**Issue by daita** [nextcloud/social#1005] opened 2020-09-10 22:05 UTC
features that should be available to a user. from the settings page

- Export data, 
- Remove data, 
- Import data.

feature for admin:

- domain migration, allowing admin to migrate nextcloud domain name.

**Comment by jancborchardt** [comment] 2020-10-15 12:37
Closing as duplicate of https://github.com/nextcloud/social/issues/118

**Closed by jancborchardt** 2020-10-15 12:37 UTC
Labels: enhancement, priority
