### ISSUE TITLE
Documenting weirdness with Social app update

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/social#1093] opened 2020-10-21 01:46 UTC
So this afternoon I updated a bunch of apps from the Nextcloud WebUI. After it attempted to update social, Nextcloud stopped working entirely and said Upgrade required. I have no idea what happened here, but I fixed it with 
```
sudo bash /var/scripts/update.sh
nextcloud_occ app:disable social
sudo reboot
```

**Comment by kowalski7cc** [comment] 2020-10-21 21:59
It seems the same issue DasSkelett (and I) found: https://github.com/nextcloud/social/issues/1034#issuecomment-712907192

**Comment by jancborchardt** [comment] 2020-10-22 12:26
Thanks for the catch @kowalski7cc – closing this as duplicate of #1034 then. :)

**Closed by jancborchardt** 2020-10-22 12:26 UTC
