### ISSUE TITLE
nginx + snap nextcloud  + social app dont work :(

### ISSUE THREAD

**Issue by suffixbabai** [nextcloud/social#452] opened 2019-03-03 09:46 UTC
Ubuntu 18.04
Nextcloud 15.0.5 (snap)
Social app 0.1.4
Nginx 1.14.0

1.
`curl https://suffix.cloud/.well-known/webfinger?resource=acct:suffix@suffix.cloud`

`{"subject":"acct:suffix@suffix.cloud","links":[{"rel":"self","type":"application\/activity+json","href":"https:\/\/suffix.cloud\/index.php\/apps\/social\/@suffix"}]}`

2.
`curl -H "Accept: application/ld+json" -X GET https://suffix.cloud/apps/social/@suffix`

`404 Not Found
The requested URL /apps/social/@suffix was not found on this server.`

3.

nginx conf

server {
    listen 80 default_server;
    listen 443 default_server ssl;

server_name suffix.cloud www.suffix.cloud;

ssl_certificate "ssl/suffix.cloud.crt";
    ssl_certificate_key "ssl/suffix.cloud.key";

location / {
proxy_pass https://127.0.0.1:444/;
proxy_redirect https://127.0.0.1:444/ /;
include /etc/nginx/proxy_params;
access_log /var/log/nginx/nextcloud-access.log;
error_log /var/log/nginx/nextcloud-error.log;
    }
}

4.

`/var/snap/nextcloud/common/nextcloud/data# cat .htaccess`

Generated by Nextcloud on 2019-03-03 00:39:13
ifModule mod_authz_core.c
Require all denied
/ifModule

ifModule !mod_authz_core.c
deny from all
Satisfy All
/ifModule

ifModule mod_autoindex.c
IndexIgnore *
/ifModule

Help me please !

**Comment by daita** [comment] 2019-03-04 12:21
Can you please try this: 

`./occ social:reset` and at the end of the process, set the url to `https://suffix.cloud/index.php`

**Comment by suffixbabai** [comment] 2019-03-04 12:33
> Can you please try this:
> 
> `./occ social:reset` and at the end of the process, set the url to `https://suffix.cloud/index.php`

Of course, I already did. I first read all similar topics here. But it did not help.

**Comment by suffixbabai** [comment] 2019-03-06 07:13
:(

**Comment by daita** [comment] 2019-05-28 09:03
might be fixed in next major release alpha2

**Comment by daita** [comment] 2019-07-04 14:19
please confirm the issue is fixed in 0.2.6

**Closed** 2020-09-24 15:11 UTC
Labels: bug, needs info
