### ISSUE TITLE
Switch to common AP backend library?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/social#501] opened 2019-04-25 22:17 UTC
**Is your feature request related to a problem? Please describe.**
Development of this app seems to have slowed down a lot... while still missing a lot of vital AP features for it to become really usable. Thus it would probably good to find ways to reduce the workload and utilize standards libraries.

**Describe the solution you'd like**
There is a new php-activitypub library that was specifically created to allow PHP projects to implement ActivityPub easily. It was created out of the Pterotype Wordpress plugin which is quite widely compatible. See:
https://github.com/pterotype-project/activitypub-php

So I think it would make sense to join forces and pull this in as an external dependency.

**Comment by jdormit** [comment] 2019-04-28 14:40
Developer of ActivityPub-PHP here. Happy to collaborate - the library is probably still a month or two out from being usable, but I would love start talking about adoption in the wider AP community.

**Comment by lafnlab** [comment] 2019-04-30 16:49
I'm interested in anything that will make it easier to federate apps. I've working off and on on Amore, but haven't implemented ActivityPub yet. ActivityPub-PHP looks like it will save people a lot of work.

**Comment by daita** [comment] 2019-05-17 21:28
Thank for your support, however the issue is not with the ActivityPub itself, but the lack of developer for the front-end of the app.

**Comment by daita** [comment] 2019-05-17 21:35
Anyone good with Vue is welcomed !

**Comment by daita** [comment] 2019-07-04 12:48
Closing this issue

**Closed by daita** 2019-07-04 12:48 UTC
Labels: enhancement
