### ISSUE TITLE
make dev-setup fail to run

### ISSUE THREAD

**Issue by ch1ch0gz** [nextcloud/social#1273] opened 2021-06-09 17:25 UTC
Hi,

When installing social on nextcloud following the instructions I get the following error when running "make dev-setup" :

npm ERR! make[1]: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.19.0-13-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /var/www/nextcloud/apps/social/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.0.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

I am using:
node --version = v16.0.0
npm --version =  v7.10.0

Do you need any other info from me?

Thanks,
Angel

**Comment by artonge** [comment] 2023-01-04 14:55
Probably a duplicate of https://github.com/nextcloud/social/issues/1557

Else can you clean your node_modules and retry ?

**Closed by artonge** 2023-01-04 14:55 UTC
