### ISSUE TITLE
Sanitize, parse and rewrite content of notes

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/social#328] opened 2019-01-11 12:13 UTC
Right now we just strip all tags from the content and parse the plain text of notes in the frontend. We match `@mentions` and `#hashtags`.

However current implementations work a bit differently and use some html wrapping for mentions and hashtags like this:

## Mastodon

```
<p>
  <span class="h-card">
    <a href="https://mastodon.xyz/@nextcloud" class="u-url mention">
      @<span>nextcloud</span>
    </a>
  </span> 
  <span class="h-card">
    <a href="https://mastodon.social/@meneer" class="u-url mention">
      @<span>meneer</span>
    </a>
  </span>
  Ticking boxes makes me wary; where are the brains? 
  <a href="https://mastodon.nl/tags/gdpr" class="mention hashtag" rel="tag">
    #<span>GDPR</span>
  </a>
</p>
```

## Friendica

```
    "content": "@<span class=\"vcard\"><a href=\"https://test.artificial-owl.com/apps/social/@cult\" class=\"url\" title=\"cult\"><span class=\"fn nickname mention\">cult</span></a></span> #<a href=\"https://squeet.me/search?tag=test\" class=\"tag\" title=\"test\">test</a> ouila",

```

This has the issue that right now, if someone creates a post mentioning
`@nextcloud@mastodon.social and @nextcloud@mastodon.xyz` we will link both to just the local `@nextcloud` account.

So we need to implement the following:
- Properly sanitize the html in content
- Rewrite urls stated in `.u-url.mention` and `.mention.hashtag` to our local routes

Refs: 
- https://www.w3.org/TR/activitystreams-vocabulary/#microsyntaxes
- https://github.com/tootsuite/mastodon/blob/8069fd636ba14059524303ce76abe2173c4f3d01/app/lib/formatter.rb#L235-L251

**Comment by annando** [comment] 2019-01-14 08:49
Concerning the mentioning I suggest having a look at the "tag" element in the post. This should always contain the links to the hashtags and mentioned profiles, so that you don't need to parse the body itself.

**Comment by daita** [comment] 2019-01-14 09:20
Mention and Hastags (#295) are using the "tag" element, however, we're trying to figure out how to replace the link in the message to fit the local instance

**Comment by daita** [comment] 2019-01-14 10:01
That is a nice (and quickly to implement) idea, however we should also check for malicious code in the content

**Comment by StCyr** [comment] 2019-09-09 11:34
hashstag should be handled correctly now.

Also, for mentions, see https://github.com/nextcloud/social/pull/667 for a proposal how to rewrite mastodon's mentions.

**Comment by daita** [comment] 2020-09-11 11:47
duplicate of #1008  - however let's keep this one opened

**Closed** 2020-10-08 21:22 UTC
Labels: 1. to develop, bug, federation
