### ISSUE TITLE
Failed to create post error

### ISSUE THREAD

**Issue by imattau** [nextcloud/social#339] opened 2019-01-16 05:27 UTC
Posting to timeline with a public post resulting in failure to create post

**Client details:**
 - OS: Andriod
 - Browser Firefox
 - Version 64
 - Device: Samsung Tab S4

**Social app version:**
0.1.2
**Operating system**:
Linux
**Database:**
Mysql (MariaDB)
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
15.02
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
500 - {"status":-1,"exception":"JsonLdException","message":"Could not convert input to RDF dataset before normalization."}

**Comment by Tealk** [comment] 2019-03-27 15:08
Have the same Problem.

**Client details:**
- OS: Windows
- Browser: Firefox

**Social app version:**
0.1.4
**Operating system**:
Debian Stretch
**Database:**
Mysql (MariaDB)
**PHP version:**
7.3
**Nextcloud version:**
15.0.5
**Logs:**
`{"reqId":"890P463T6dCdjIVgoIWG","level":2,"time":"27.03.2019 16:00:32","remoteAddr":"212.211.192.4","user":"xxx","app":"no app in context","method":"POST","url":"\/apps\/social\/api\/v1\/post","message":"500 - {\"status\":-1,\"exception\":\"JsonLdException\",\"message\":\"Could not convert input to RDF dataset before normalization.\"}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"15.0.5.3"}`

**Comment by yonatanmm** [comment] 2019-04-04 08:56
help:  failed to create post using social app

**Comment by daita** [comment] 2019-07-04 13:10
is it fixed in 0.2.6 ?

**Comment by Tealk** [comment] 2019-07-04 13:43
I don't get an error message when I make a post but I don't see it anywhere.
And I don't even see subscriptions anymore.

**Comment by daita** [comment] 2019-08-22 15:28
try `./occ social:check:install`

**Comment by daita** [comment] 2020-09-24 15:11
Please re-open this issue if the issue is still not fix

**Closed by daita** 2020-09-24 15:11 UTC
Labels: bug, needs info

**Comment by ptandler** [comment] 2021-12-14 10:15
I have this issue as well, when I try to post (public or to followers), I get the message "failed to create post", nothing in the logs that seems to be related, the input field keeps a spinning wheel forever.

**Nextcloud** 21.0.7
**Social App** 0.4.2
**PHP** 7.4.26
**Browser** Firefox 95.0

@ArtificialOwl the output of `./occ social:check:install` contains nothing I'd regard as an issue ...?

```
bash-4.4$ ./occ social:check:install
The current PHP memory limit is below the recommended value of 512MB.
- 0 invalid followers removed
- 0 invalid notes removed

- Your current configuration: 
{
    "cloud_url": "...",
    "social_url": "...\/apps\/social\/",
    "social_address": "",
    "service": 1,
    "max_size": 10,
    "access_type": "all_but",
    "access_list": "[]",
    "allow_self_signed": "0",
    "db_chunk_size": 10000
}
```
