### ISSUE TITLE
Mentions in toots get linked to local accounts instead of remote information

### ISSUE THREAD

**Issue by rhonda** [nextcloud/social#585] opened 2019-06-18 08:43 UTC
**Describe the bug**

In the global timeline I have toots with a fair amount of mentions from accounts that I follow remotely.  When those contain @ mentions of other accounts, those are considered to be local accounts and link to /apps/social/@user which doesn't exist instead of /apps/social/@user@server/ which would bring up the profile information for the remote account

**Comment by StCyr** [comment] 2019-08-01 13:09
The problem is that the content field in the DB is already wrong.

For example, here's a content mentioning a `@tcit` account:

`<p><span class="h-card"><a href="https://social.tcit.fr/@tcit" class="u-url mention">@<span>tcit</span></a></span> Ah, good ol&apos; Avocado&apos;s Number.</p>`

while the mention in fact relates to `@tcit@social.tcit.fr`

And, this content field is probably wrong because the toot 'source is already mentioning a shortened version of this account:

`{"id":"https://bsd.network/users/ed1conf/statuses/102508418934680823","type":"Note","summary":null,"inReplyTo":"https://social.tcit.fr/users/tcit/statuses/102503134249985524","published":"2019-07-26T15:19:01Z","url":"https://bsd.network/@ed1conf/102508418934680823","attributedTo":"https://bsd.network/users/ed1conf","to":["https://www.w3.org/ns/activitystreams#Public"],"cc":["https://bsd.network/users/ed1conf/followers","https://social.tcit.fr/users/tcit"],"sensitive":false,"atomUri":"https://bsd.network/users/ed1conf/statuses/102508418934680823","inReplyToAtomUri":"https://social.tcit.fr/users/tcit/statuses/102503134249985524","conversation":"tag:social.tcit.fr,2019-07-25:objectId=5788322:objectType=Conversation","content":"<p><span class=\"h-card\"><a href=\"https://social.tcit.fr/@tcit\" class=\"u-url mention\">@<span>tcit</span></a></span> Ah, good ol&apos; Avocado&apos;s Number.</p>","contentMap":{"af":"<p><span class=\"h-card\"><a href=\"https://social.tcit.fr/@tcit\" class=\"u-url mention\">@<span>tcit</span></a></span> Ah, good ol&apos; Avocado&apos;s Number.</p>"},"attachment":[],"tag":[{"type":"Mention","href":"https://social.tcit.fr/users/tcit","name":"@tcit@social.tcit.fr"}],"replies":{"id":"https://bsd.network/users/ed1conf/statuses/102508418934680823/replies","type":"Collection","first":{"type":"CollectionPage","partOf":"https://bsd.network/users/ed1conf/statuses/102508418934680823/replies","items":[]}}}`

The only place where the full account name is defined is in the 'tag' field of the toot 'source.

**Comment by daita** [comment] 2019-09-15 13:34
- if authed user clicks on a remote account, displays the account locally, with option 'follow' and a link to the account on the remote instance,
- if not authed user clicks on a remote account, display the account from the remote instance.

**Comment by daita** [comment] 2020-09-11 11:47
duplicate of #1008 - however let's keep this one opened

**Closed** 2020-10-08 21:22 UTC
Labels: bug
