### ISSUE TITLE
Server name in handle is @localhost

### ISSUE THREAD

**Issue by rev138** [nextcloud/social#265] opened 2018-12-21 20:12 UTC
**Describe the bug**
The social handle displayed above the new post form is @username@localhost

**To Reproduce**
1. Go to 'Social'
2. See error

**Expected behavior**
I would expect to see @username@example.com

**Screenshots**
![screenshot from 2018-12-21 15-03-03](https://user-images.githubusercontent.com/1538633/50361546-eed53f80-0531-11e9-93cd-fe4d8693932f.png)

**Client details:**
 - OS: Fedora 29
 - Browser Firefox
 - Version 64.0
 - Device: PC

<details>
<summary>Server details</summary>

**Social app version:** 0.1.0

**Operating system**: debian 9

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.2

**Nextcloud version:** 15.0.0

</details>

<details>

**Comment by rev138** [comment] 2018-12-21 20:54
I took a look in the database:
```
MariaDB [nextcloud]> select * from oc_appconfig where configvalue like '%localhost%';
+--------+-----------+------------------+
| appid  | configkey | configvalue      |
+--------+-----------+------------------+
| social | address   | http://localhost |
+--------+-----------+------------------+
1 row in set (0.005 sec)
```
I manually updated it to my domain name (minus the http://) and now it displays correctly in the app.

**Comment by rev138** [comment] 2018-12-21 21:06
Further, looking in  social/lib/Controller/NavigationController.php:

```
private function setupCloudAddress(): string {
        ...
	$cloudAddress = rtrim($this->config->getSystemValue('overwrite.cli.url', ''), '/');
        ...
}

```
In my config.php, `overwrite.cli.url` is indeed set to 'http://localhost'.

**Comment by violoncelloCH** [comment] 2018-12-21 21:46
exactly, I think we can treat this as a duplicate of #233 ?

**Closed** 2018-12-21 21:50 UTC
Labels: bug, duplicate

**Comment by daita** [comment] 2018-12-21 22:08
Yes, using the occ social:reset command would help to setup another address

**Comment by pred2k** [comment] 2021-01-31 09:28
I'm posting here because the issue is close but still a thing with a fresh installation via snap on Ubuntu 20.04.

```
root@TEST-SERVER:~# nextcloud.occ status
  - installed: true
  - version: 20.0.4.0
  - versionstring: 20.0.4
  - edition:
root@TEST-SERVER:~# nextcloud.occ config:system:get trusted_domains
localhost
cloud.<mydomain>
```

Could the the reason be that localhost is the first entry in trusted_domains?
