### ISSUE TITLE
Please restart the project

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/social#1366] opened 2022-04-06 14:20 UTC
Dear Community!
This was a great idea to have the possibility of your own little social network.
I think in future that can be a big run and a good and private competition to the big players as facebook,...
Nextcloud Talk is already really nice for chatting.
But like a socila media platform in within the cloud would be genius.

**Comment by violoncelloCH** [comment] 2022-04-14 21:42
thanks for your kind works... this seems to be more or less a duplicate of #1290

**Closed by violoncelloCH** 2022-04-14 21:42 UTC
Labels: enhancement
