### ISSUE TITLE
i am unable to download this app 

### ISSUE THREAD

**Issue by bitfanatic** [nextcloud/social#1295] opened 2021-07-28 15:17 UTC
**after i push the download button it looks like it tries to to download but aborts and shows this message

Could not extract app social: Out-of-path 
file extraction {/tmp/oc_tmp_y5lESO-folder/social/vendor/bin/parallel-lint --> 
../jakub-onderka/php-parallel-lint/parallel-lint} **

i dont know what is wrong

**Comment by florianajir** [comment] 2021-08-11 22:31
same here, unusable

**Comment by smokinjo** [comment] 2021-09-03 20:09
I tried insalling it h epast few days.  I get he sam error:

 Could not extract app social: Out-of-path file extraction {/var/www/clients/client1/web13/tmp/oc_tmp_kH8rld-folder/social/vendor/bin/parallel-lint --> ../jakub-onderka/php-parallel-lint/parallel-lint} 

I am using NC on Ubuno 20.04, php 7.4, maria db 10.3, apache ???

I've been using Friendica which I like.

I want to try social to try it for awhile.

Hopefully the developpers are able to get back to us about what the causes might be.

Joseph

**Comment by CarlSchwan** [comment] 2022-04-15 17:03
Should be fixed with https://github.com/nextcloud/social/pull/1377

**Comment by artonge** [comment] 2023-01-04 14:52
Duplicate https://github.com/nextcloud/social/issues/1505

**Closed by artonge** 2023-01-04 14:52 UTC
Labels: bug
