### ISSUE TITLE
Group integration via !bang tags

### ISSUE THREAD

**Issue by poVoq** [nextcloud/social#427] opened 2019-02-18 18:44 UTC
**Is your feature request related to a problem? Please describe.**
Would be nice to allow people to write to a group on Nextcloud social and have automatically a group channel that can be written to by using the !bang tag like in Friendica, Hubzilla or GNUSocial.

**Describe the solution you'd like**
Compatible group / forum channel implementation similar to Friendica or Hubzilla on ActivityPub that you can follow via `*groupname*@yournextclouddomain.xyz` and write to via `!*groupname*@nextclouddomain.xyz`
Groups should be of course created from the Nextcloud internal groups and/or maybe circles.

Thanks for considering.

**Comment by juliushaertl** [comment] 2019-02-19 07:03
@daita Duplicate of #231 but it seems this is a possible solution on how the implementation could be handled.

**Comment by poVoq** [comment] 2019-02-19 07:58
Sorry didn't see the other issue.

@annando since you (?) recently implemented the same thing on ActivityPub for Friendica, any tips? Maybe there is even a chance to share some php code?

**Comment by annando** [comment] 2019-02-19 08:52
Code sharing won't be possible since most of the group handling is not in the AP implementation but the core.

The idea that we want to implement (we are not completely done at the moment) is that when writing a post with a ```!```, then the message is public, but only sent to the group account. The group account then receives the posts. It recognizes the ```!``` and does an ```Announce``` of this message to the followers of the group account.

**Comment by daita** [comment] 2019-02-19 10:18
This will be a needed feature; and the implementation of a !bang seems fun enough.

I will have a look on how Group as Actor can be handled.

**Comment by juliushaertl** [comment] 2019-02-20 20:17
Let's track this in #231

**Closed by juliushaertl** 2019-02-20 20:17 UTC
Labels: enhancement
