### ISSUE TITLE
Nextcloud does not seem to work with ActivityPub clients like Roma

### ISSUE THREAD

**Issue by apcameron** [nextcloud/social#834] opened 2019-12-21 02:10 UTC
When I try to log on it fails with the following entry in the Nextcloud logs
 "POST /api/v1/apps HTTP/1.1" 404 282

**Comment by spaetz** [comment] 2020-01-08 09:04
These clients use the Mastodon API which is not implemented in Nextcloud social as it is strictly speaking not part of ActivityPub. There is an issue about this #145.

**Comment by violoncelloCH** [comment] 2020-02-21 18:50
yes, as @spaetz said... closing this as a duplicate of #145

**Closed by violoncelloCH** 2020-02-21 18:50 UTC
